### ISSUE TITLE
Compiled version

### ISSUE THREAD

**Issue by ndrefg** [antonycaporossi/Tachiyomi-Readcomiconline-Extension#1]
Hi! would you be able to compile the apk for and put it on releases please? 

Thank you very much for continuing the extension. I tried to do it but I seem to know next to nothing of the language 🥂

**Comment by antonycaporossi** [comment]
Yes sure, tomorrow i will upload the APK. I'll notify you here once is online

**Comment by antonycaporossi** [comment]
[Compiled version uploaded
](https://github.com/antonycaporossi/Tachiyomi-Readcomiconline-Extension/releases)

**Comment by ndrefg** [comment]
Thank you!
