### ISSUE TITLE
Advanced Search - Genre is ignored when searching

### ISSUE THREAD

**Issue by stebaker92** [antonycaporossi/Tachiyomi-Readcomiconline-Extension#4]
Not sure if this is related to issue #2 at all but Genre seems to be ignored when doing an Advanced Search. i.e. when selecting the `Zombies` genre, all comics seem to come back

My guess would be the URL being generated here is wrong:
https://github.com/antonycaporossi/Tachiyomi-Readcomiconline-Extension/blob/3836273c03f8541d07df6de60fc39ebf6e2c0e86/readcomiconline/src/eu/kanade/tachiyomi/extension/en/readcomiconline/Readcomiconline.kt#L82

It should be something like this, where `ig` is a comma separated list of the Genres a user has selected (and `eg` is Genres the user has explicitly excluded):
`/AdvanceSearch?comicName=&ig=1%2C36%2C&eg=&status=`

(I might attempt to pick this up at some point but have no experience building Tachiyomi extensions or Kotlin in general)

**Comment by antonycaporossi** [comment]
Hello, thank you for the report.
It seems that Readcomiconline changed their Advanced search method from POST to GET.
Also the Genre has an include and eclude status.
I've fixed the problem and the release will be available today.
