### ISSUE TITLE
Unable to install latest release

### ISSUE THREAD

**Issue by stebaker92** [antonycaporossi/Tachiyomi-Readcomiconline-Extension#6]
The previous APK installed fine but the latest release fails to install (I've tried uninstalling the previous version first), let me know if you need any more details

![Screenshot_20220524-132046](https://user-images.githubusercontent.com/11291329/170033649-c22eb881-103f-41ef-b19a-0817fa3627d9.png)

**Comment by antonycaporossi** [comment]
Hello, my bad.
I uploaded a new [APK](https://github.com/antonycaporossi/Tachiyomi-Readcomiconline-Extension/releases/tag/v1.2.13)

Try it and let me know. Thanks!

**Comment by stebaker92** [comment]
APK works fine now, thanks for fixing so quickly!
